name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coding-standards:
    name: "Coding standards"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: PSR12
      run: ./vendor/squizlabs/php_codesniffer/bin/phpcs -n --colors --report=full --standard=PSR12 --extensions=php ./src
    - name: PHPMD
      run: ./vendor/phpmd/phpmd/src/bin/phpmd ./src ansi ./ruleset.xml
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Dump JWT Lexik keypair"
        run: ./bin/console lexik:jwt:generate-keypair --no-interaction --overwrite
      - name: "Run PHPUnit"
        run: ./vendor/phpunit/phpunit/phpunit ./tests --bootstrap=./tests/bootstrap.php --testdox
      
      
